// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXItq7z1oqzsTM9IsTP3JP4xGCtqKXnnM',
    appId: '1:703927130700:web:38b4cb520f3156fb6c32e9',
    messagingSenderId: '703927130700',
    projectId: 'quado-jjkl',
    authDomain: 'quado-jjkl.firebaseapp.com',
    storageBucket: 'quado-jjkl.appspot.com',
    measurementId: 'G-FXX08P55TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwurV1uQr3cifPtv9WYRYEql-Dl1uBsF0',
    appId: '1:703927130700:android:c53d4b9bb1987a196c32e9',
    messagingSenderId: '703927130700',
    projectId: 'quado-jjkl',
    storageBucket: 'quado-jjkl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnSazIJuBuWfE_5xLFbiNwlsRIcLPigw',
    appId: '1:703927130700:ios:7eca9c34a126f2d86c32e9',
    messagingSenderId: '703927130700',
    projectId: 'quado-jjkl',
    storageBucket: 'quado-jjkl.appspot.com',
    iosClientId: '703927130700-i60ems4safi4e4hs998k266s9hhv45le.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0415',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlnSazIJuBuWfE_5xLFbiNwlsRIcLPigw',
    appId: '1:703927130700:ios:7eca9c34a126f2d86c32e9',
    messagingSenderId: '703927130700',
    projectId: 'quado-jjkl',
    storageBucket: 'quado-jjkl.appspot.com',
    iosClientId: '703927130700-i60ems4safi4e4hs998k266s9hhv45le.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0415',
  );
}
